### ISSUE TITLE
About plot in your article

### ISSUE THREAD

**Issue by zhoudreames** [marbl/SALSA#143]
I am so happy to gain the good result by using  your Salsa software,and  i want to show this plot in my article.this plot is no good by using your recommend coloredChromosomes software,This may be a problem with my usage，I would like to ask if you can provide code to me ?thanks~
![image](https://user-images.githubusercontent.com/54714639/125557672-43be2da7-79c5-43ac-9d8a-2739f042028b.png)

**Comment by skoren** [comment]
The plots are generated using the same code as in the MHAP publication () so the code is available as supplementary materials from that publication here: http://www.cbcb.umd.edu/software/PBcR/MHAP/. However, coloredChromosomes is no longer maintained and it can be quite difficult to reconfigure it's display other genomes (e.g. not human). 

More recently, we have been using https://github.com/bernatgel/karyoploteR which is an active project and has extensive documentation, including using it for custom genomes. It can visualize any intervals so you can reproduce the above plot assuming you have alignment blocks to a reference. I recommend learning/using karyoploteR instead of coloredChromosomes.
