### ISSUE TITLE
Can SALSA be used with CHICAGO library sequencing reads

### ISSUE THREAD

**Issue by YuanwenGuo** [marbl/SALSA#79]
Hi,
Thank you for developing SALSA, which improves our assembly tremendously by adding Hi-C data. 
Since we also have CHICAGO library sequencing reads in addition to Hi-C data, I was wondering if SALSA can be applied for CHICAGO as well? Actually, I tried to use SALSA with CHICAGO, but seems like the assembly is not improved a lot (N50 and longest contig is even reduced compared with input assembly). 
I will much appreciate if you could help me with this issue.

Best,
Yuanwen

**Comment by skoren** [comment]
Salsa can use Chicago data but, as you saw, it will not improve the NG50 as much as the HiC data due to the shorter-range interaction lengths. There isn't support in Salsa to use both datatypes simultaneously with different weights for each so I would suggest just using the HiC data since you have it.

**Comment by YuanwenGuo** [comment]
Thank you very much for the response! We will only use HiC data at this moment as you suggested.

Best,
Yuanwen
