### ISSUE TITLE
Reg: Key-Error in Unitig stitching

### ISSUE THREAD

**Issue by harish0201** [marbl/SALSA#82]
Hi,

I have scaffolded the Unitigs produced from Canu using SALSA using the contig-tiling bed file from Canu as well.

I'm attaching the log files and the bed file. The error seems to occur while stitching "tig00005760". 

Can you let me know what should be done in this case? 

[pp_canu.unitigs.bed.txt](https://github.com/marbl/SALSA/files/3534293/pp_canu.unitigs.bed.txt)
[log.txt](https://github.com/marbl/SALSA/files/3534294/log.txt)

**Comment by skoren** [comment]
How did you run Salsa to generate this assembly? It looks from the log like you ran with unitig correction. Typically when we input unitigs we turn off correction. The issue is the names are changed by the correction splitting so the error you're getting is because the newly created corrected unitigs don't exist in the bed file. As a workaround, I would suggest removing the entry for the offending tig:
```
ctg00018212	0	104147	utg00005758	0	+
ctg00018212	88892	130570	utg00005759	0	+
ctg00018212	108611	1674855	utg00005760	0	+
ctg00018212	1654014	1686987	utg00005761	0	+
```
and create new contigs for each of those tigs:
```
ctg99999990	0	104147	utg00005758	0	+
ctg99999991 	88892	130570	utg00005759	0	+
ctg99999992	108611	1674855	utg00005760_1	0	+
ctg99999993	108611	1674855	utg00005760_2	0	+
ctg99999994	1654014	1686987	utg00005761	0	+
```
If you have other split unitigs (with the _), you'll need to repeat the process for those as well. Let us know if that works.

**Comment by harish0201** [comment]
Yup, I believe I did run with unitig correction! Sure, I'll try removing the offending tigs.

Thank for the help
