### ISSUE TITLE
why SALSA breaks contigs into two scaffolds

### ISSUE THREAD

**Issue by sisyyuan** [marbl/SALSA#84]
Hi!
When I got my scaffolds after SALSA, I found that the busco score dropped around 20% from that of contigs. I checked the .agp file and found that 3 contigs were split into different scaffolds. 

Does anybody know why?
Thanks!

**Comment by skoren** [comment]
SALSA splits contigs when there is low support for them from HiC data. 

Either way, a split of 2-3 contigs should not drop BUSCO score by 20%, that seems like an issue with the second BUSCO run rather than a split. You could look at individual genes that were in the split contigs and their coordinates to compare them to a split. They should only be affected if they span the split positions.

**Comment by harish0201** [comment]
Just want to put this out @sisyyuan , sometimes BUSCO runs can have this issue, because tblastn can encounter a bug if its being run using multiple cores/threads.
